### ISSUE TITLE
!give bug

### ISSUE THREAD

**Issue by Orrlaa** [Rx4Byte/SunHaven#8]
when using the !give mod the game will freeze on a black screen when moving between roads and cant get past the black screen

**Comment by wolfitdm** [comment]
Fixed here

https://github.com/wolfitdm/SunHavenEx/blob/30264b948e4bbb7aeaa2b3c6c68e29825d96d188/CommandExtension/CommandExtension.cs#L1502

Your mod, with all my fixes:

https://www.nexusmods.com/sunhaven/mods/390
